ALTER TYPE "BulkImportStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_COMPLETED';
ALTER TYPE "BulkImportStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "BulkImportJob"
  ADD COLUMN IF NOT EXISTS "skippedRows" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "warningRows" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "warningSummary" JSONB,
  ADD COLUMN IF NOT EXISTS "previewSummary" JSONB,
  ADD COLUMN IF NOT EXISTS "resultSummary" JSONB,
  ADD COLUMN IF NOT EXISTS "uploadedAt" TIMESTAMP(3);
