ALTER TABLE "PreReservation" ADD COLUMN "billingLegalOrganizationType" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingIdentificationDocumentType" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingIdentificationNumber" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingVerificationDigit" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingCustomerName" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingEmail" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingPhone" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingDepartment" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingMunicipalityId" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingMunicipalityName" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingAddress" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingTaxResponsibility" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingTributeId" TEXT;
ALTER TABLE "PreReservation" ADD COLUMN "billingDataAccepted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PreReservation" ADD COLUMN "billingIsComplete" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Booking" ADD COLUMN "billingLegalOrganizationType" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingIdentificationDocumentType" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingIdentificationNumber" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingVerificationDigit" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingCustomerName" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingEmail" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingPhone" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingDepartment" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingMunicipalityId" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingMunicipalityName" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingAddress" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingTaxResponsibility" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingTributeId" TEXT;
ALTER TABLE "Booking" ADD COLUMN "billingDataAccepted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Booking" ADD COLUMN "billingIsComplete" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "CompanySettings" ADD COLUMN "factusEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CompanySettings" ADD COLUMN "factusMode" TEXT NOT NULL DEFAULT 'mock';
ALTER TABLE "CompanySettings" ADD COLUMN "factusNumberingRangeId" TEXT;
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultDocumentCode" TEXT NOT NULL DEFAULT '01';
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultPaymentForm" TEXT;
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultPaymentMethodCode" TEXT;
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultUnitMeasureId" TEXT;
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultStandardCodeId" TEXT;
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultTributeId" TEXT;
ALTER TABLE "CompanySettings" ADD COLUMN "factusDefaultMunicipalityId" TEXT;
