ALTER TABLE "PreReservation"
ADD COLUMN "adults" INTEGER,
ADD COLUMN "children" INTEGER,
ADD COLUMN "infants" INTEGER,
ADD COLUMN "manualAdjustmentAmount" DOUBLE PRECISION,
ADD COLUMN "lastModifiedById" INTEGER,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

