type AuditActor = {
  userId?: number;
  role?: string;
  name?: string;
  email?: string;
};

type SlugAuditRecorder = {
  record(data: {
    actor?: AuditActor;
    action: string;
    entityType: string;
    entityId: string | number;
    message?: string;
    previousValue?: unknown;
    newValue?: unknown;
    metadata?: Record<string, unknown>;
  }): Promise<void>;
};

type SlugAuditOptions = {
  audit: SlugAuditRecorder;
  actor?: AuditActor;
  entityType: string;
  entityId: string | number;
  operation: "create" | "update";
  previousSlug?: string | null;
  baseSlug: string;
  finalSlug: string;
  wasAutoGenerated: boolean;
  sourceField: "title" | "name";
};

export async function recordSlugAudit({
  audit,
  actor,
  entityType,
  entityId,
  operation,
  previousSlug,
  baseSlug,
  finalSlug,
  wasAutoGenerated,
  sourceField,
}: SlugAuditOptions) {
  const cleanPreviousSlug = previousSlug?.trim() || null;
  const cleanBaseSlug = baseSlug.trim();
  const cleanFinalSlug = finalSlug.trim();

  if (!cleanFinalSlug) return;

  if (operation === "create") {
    await audit.record({
      actor,
      action: "SLUG_CREATED",
      entityType,
      entityId,
      message: `Slug creado: ${cleanFinalSlug}`,
      newValue: { slug: cleanFinalSlug },
      metadata: { sourceField },
    });
  }

  if (operation === "update" && cleanPreviousSlug !== cleanFinalSlug) {
    await audit.record({
      actor,
      action: "SLUG_UPDATED",
      entityType,
      entityId,
      message: `Slug actualizado: ${cleanFinalSlug}`,
      previousValue: { slug: cleanPreviousSlug },
      newValue: { slug: cleanFinalSlug },
      metadata: { sourceField },
    });
  }

  if (wasAutoGenerated) {
    await audit.record({
      actor,
      action: "SLUG_AUTO_GENERATED",
      entityType,
      entityId,
      message: `Slug autogenerado: ${cleanFinalSlug}`,
      newValue: { slug: cleanFinalSlug },
      metadata: { sourceField },
    });
  }

  if (cleanBaseSlug && cleanBaseSlug !== cleanFinalSlug) {
    await audit.record({
      actor,
      action: "SLUG_DUPLICATE_RESOLVED",
      entityType,
      entityId,
      message: `Slug duplicado resuelto: ${cleanFinalSlug}`,
      previousValue: { requestedSlug: cleanBaseSlug },
      newValue: { slug: cleanFinalSlug },
      metadata: { sourceField },
    });
  }
}
