-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "allowsPets" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "checkInTime" TEXT,
ADD COLUMN     "checkOutTime" TEXT,
ADD COLUMN     "extraGuestIncrease" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "features" TEXT,
ADD COLUMN     "highSeasonPrice" DOUBLE PRECISION,
ADD COLUMN     "lowSeasonPrice" DOUBLE PRECISION,
ADD COLUMN     "maxCapacity" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "minimumNights" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "twoGuestsIncrease" DOUBLE PRECISION NOT NULL DEFAULT 0;
