const actionLabels: Record<string, string> = {
  ADVISOR_ASSIGNED: "Asesor asignado",
  BOOKING_CONFIRMED: "Reserva confirmada",
  BOOKING_CREATED: "Reserva creada",
  BLOG_POST_CREATED: "Articulo de blog creado",
  BLOG_POST_DELETED: "Articulo de blog eliminado",
  BLOG_POST_PUBLISHED: "Articulo de blog publicado",
  BLOG_POST_UNPUBLISHED: "Articulo de blog despublicado",
  BLOG_POST_UPDATED: "Articulo de blog actualizado",
  BULK_IMPORT_COMPLETED: "Importación masiva completada",
  BULK_IMPORT_FAILED: "Importación masiva fallida",
  BULK_IMPORT_STARTED: "Importación masiva iniciada",
  CHECKOUT_CURRENCY_APPLIED: "Moneda aplicada en checkout",
  CONTACT_CREATED: "Contacto creado",
  DESTINATION_CREATED: "Destino creado",
  DESTINATION_DELETED: "Destino eliminado",
  DESTINATION_RELATIONS_UPDATED: "Relaciones de destino actualizadas",
  DESTINATION_STATUS_UPDATED: "Estado de destino actualizado",
  DESTINATION_UPDATED: "Destino actualizado",
  ERROR: "Error registrado",
  EXCHANGE_RATE_CREATED: "Tasa de cambio creada",
  EXCHANGE_RATE_DISABLED: "Tasa de cambio desactivada",
  EXCHANGE_RATE_UPDATED: "Tasa de cambio actualizada",
  FACTUS_COP_PAYLOAD_PREPARED: "Payload COP preparado para Factus",
  FAILED: "Fallo registrado",
  INVOICE_CANCELLED: "Factura cancelada",
  INVOICE_COP_GENERATED: "Factura interna generada",
  INVOICE_CREATED: "Factura interna creada",
  INVOICE_DETAIL_VIEWED: "Detalle de factura consultado",
  INVOICE_DUPLICATE_ATTEMPT: "Intento de factura duplicada",
  INVOICE_GENERATED: "Factura interna generada",
  INVOICE_MARKED_PAID: "Factura marcada como pagada",
  INVOICE_PAYMENT_STATUS_UPDATED: "Estado de pago de factura actualizado",
  INVOICE_STATUS_UPDATED: "Estado de factura actualizado",
  PAYMENT_CURRENCY_SAVED: "Moneda de pago guardada",
  PRE_RESERVATION_CREATED: "Solicitud creada",
  PROPERTY_CREATED: "Alojamiento creado",
  PROPERTY_DELETED: "Alojamiento eliminado",
  PROPERTY_UPDATED: "Alojamiento actualizado",
  REQUEST_ASSIGNED: "Solicitud asignada",
  REQUEST_STATUS_UPDATED: "Estado de solicitud actualizado",
  REVIEW_APPROVED: "Opinión aprobada",
  REVIEW_DELETED: "Opinión eliminada",
  REVIEW_DETAIL_VIEWED: "Detalle de opinion consultado",
  REVIEW_FEATURED: "Opinion destacada",
  REVIEW_HIDDEN: "Opinion oculta",
  REVIEW_LINK_GENERATED: "Link de opinion generado",
  REVIEW_RANKINGS_VIEWED: "Rankings internos de opiniones consultados",
  REVIEW_RATING_CACHE_UPDATED: "Cache de calificacion de producto actualizado",
  REVIEW_RATING_RECALCULATED: "Calificacion de opiniones recalculada",
  REVIEW_REJECTED: "Opinion rechazada",
  REVIEW_REMINDER_FAILED: "Recordatorio de opinion fallido",
  REVIEW_REMINDER_LIMIT_REACHED: "Limite de recordatorios alcanzado",
  REVIEW_REMINDER_READY: "Recordatorio de opinion listo",
  REVIEW_REMINDER_SENT: "Recordatorio de opinion enviado",
  REVIEW_REMINDER_SKIPPED: "Recordatorio de opinion omitido",
  REVIEW_REMINDER_TOKEN_REGENERATED: "Token de recordatorio regenerado",
  REVIEW_REQUEST_ALREADY_SENT: "Solicitud de opinion ya enviada",
  REVIEW_REQUEST_EMAIL_FAILED: "Correo de solicitud de opinion fallido",
  REVIEW_REQUEST_EMAIL_SENT: "Correo de solicitud de opinion enviado",
  REVIEW_REQUEST_READY: "Solicitud de opinion lista",
  REVIEW_REQUEST_SKIPPED: "Solicitud de opinion omitida",
  REVIEW_REQUEST_WHATSAPP_PREPARED: "Mensaje de WhatsApp de opinion preparado",
  REVIEW_SCHEMA_ELIGIBLE: "Schema de opiniones elegible",
  REVIEW_SCHEMA_READY: "Schema de opiniones preparado",
  REVIEW_SET_PENDING: "Opinion marcada como pendiente",
  REVIEW_STATUS_UPDATED: "Estado de opinion actualizado",
  REVIEW_SUBMISSION_REJECTED: "Envio de opinion rechazado",
  REVIEW_SUBMITTED: "Opinion enviada",
  REVIEW_TOKEN_EXPIRED: "Token de opinion expirado",
  REVIEW_TOKEN_VALIDATED: "Token de opinion validado",
  REVIEW_UNFEATURED: "Destacado de opinion retirado",
  SETTINGS_UPDATED: "Configuracion actualizada",
  SLUG_AUTO_GENERATED: "Slug autogenerado",
  SLUG_CREATED: "Slug creado",
  SLUG_DUPLICATE_RESOLVED: "Slug duplicado resuelto",
  SLUG_UPDATED: "Slug actualizado",
  SYSTEM_HEALTH_ERROR: "Error de monitoreo del sistema",
  TRANSLATION_COMPLETED: "Traducción completada",
  TRANSLATION_FAILED: "Traducción fallida",
  TRANSLATION_JOB_CREATED: "Trabajo de traduccion creado",
  TRANSLATION_MANUAL_OVERRIDE: "Traduccion ajustada manualmente",
  TRANSLATION_REGENERATED: "Traduccion regenerada",
  TRANSLATION_STARTED: "Traducción iniciada",
};

const entityLabels: Record<string, string> = {
  AUDIT_LOG: "Registro",
  BLOG_POST: "Articulo de blog",
  BlogPost: "Articulo de blog",
  BOOKING: "Reserva",
  CONTACT: "Contacto",
  DESTINATION: "Destino",
  EXCHANGE_RATE: "Tasa de cambio",
  EXPERIENCE: "Experiencia",
  INVOICE: "Factura",
  OPERATIONAL_NOTIFICATION: "Notificacion operativa",
  PACKAGE: "Paquete",
  PAYMENT: "Pago",
  PRE_RESERVATION: "Solicitud",
  PRODUCT_FEATURE: "Caracteristica",
  PROPERTY: "Alojamiento",
  REVIEW: "Opinion",
  SYSTEM: "Sistema",
  SYSTEM_SETTINGS: "Configuracion",
  TRANSLATION_JOB: "Trabajo de traduccion",
  USER: "Usuario",
};

const fallbackWordLabels: Record<string, string> = {
  ACTION: "accion",
  APPROVED: "aprobada",
  ASSIGNED: "asignada",
  BOOKING: "reserva",
  BULK: "masiva",
  CACHE: "cache",
  COMPLETED: "completada",
  COP: "COP",
  CREATED: "creada",
  CURRENCY: "moneda",
  DELETED: "eliminada",
  DETAIL: "detalle",
  DISABLED: "desactivada",
  EMAIL: "correo",
  ERROR: "error",
  EXCHANGE: "cambio",
  FACTUS: "Factus",
  FAILED: "fallida",
  FEATURED: "destacada",
  GENERATED: "generada",
  HEALTH: "estado",
  HIDDEN: "oculta",
  IMPORT: "importacion",
  INVOICE: "factura",
  JOB: "trabajo",
  LINK: "link",
  MANUAL: "manual",
  OVERRIDE: "ajuste",
  PAYMENT: "pago",
  PENDING: "pendiente",
  PREPARED: "preparado",
  RATING: "calificacion",
  READY: "lista",
  RECALCULATED: "recalculada",
  REGENERATED: "regenerada",
  REJECTED: "rechazada",
  REMINDER: "recordatorio",
  REQUEST: "solicitud",
  REVIEW: "opinion",
  SCHEMA: "schema",
  SENT: "enviada",
  SETTINGS: "configuracion",
  SKIPPED: "omitida",
  SLUG: "slug",
  STARTED: "iniciada",
  STATUS: "estado",
  SUBMITTED: "enviada",
  SYSTEM: "sistema",
  TOKEN: "token",
  TRANSLATION: "traduccion",
  UPDATED: "actualizada",
  USER: "usuario",
  VALIDATED: "validado",
  VIEWED: "consultado",
  WHATSAPP: "WhatsApp",
};

export function readableTechnicalLabel(value?: string | null) {
  if (!value) return "Sin dato";

  const translated = value
    .split("_")
    .filter(Boolean)
    .map((word) => fallbackWordLabels[word] || word.toLowerCase())
    .join(" ");

  return translated.replace(/^\w/, (letter) => letter.toUpperCase());
}

export function auditActionLabel(action?: string | null) {
  if (!action) return "Evento registrado";
  return actionLabels[action] || readableTechnicalLabel(action);
}

export function entityTypeLabel(entityType?: string | null) {
  if (!entityType) return "Entidad";
  return entityLabels[entityType] || readableTechnicalLabel(entityType);
}

export function roleLabel(role?: string | null) {
  const labels: Record<string, string> = {
    ADMIN: "Administrador",
    ADVISOR: "Asesor",
    PUBLIC: "Publico",
    SUPERADMIN: "Superadmin",
  };

  if (!role) return "Sistema";
  return labels[role] || readableTechnicalLabel(role);
}
