ALTER TABLE "CompanySettings"
ADD COLUMN "businessName" TEXT NOT NULL DEFAULT 'Cartagena Tailored Travel',
ADD COLUMN "legalName" TEXT,
ADD COLUMN "nit" TEXT,
ADD COLUMN "phone" TEXT,
ADD COLUMN "whatsappNumber" TEXT,
ADD COLUMN "city" TEXT NOT NULL DEFAULT 'Cartagena',
ADD COLUMN "country" TEXT NOT NULL DEFAULT 'Colombia',
ADD COLUMN "websiteUrl" TEXT,
ADD COLUMN "instagramUrl" TEXT,
ADD COLUMN "facebookUrl" TEXT,
ADD COLUMN "tiktokUrl" TEXT,
ADD COLUMN "faviconUrl" TEXT,
ADD COLUMN "primaryColor" TEXT NOT NULL DEFAULT '#0D2B52',
ADD COLUMN "secondaryColor" TEXT NOT NULL DEFAULT '#B48A5A',
ADD COLUMN "defaultCurrency" TEXT NOT NULL DEFAULT 'COP',
ADD COLUMN "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "serviceFeeRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "footerText" TEXT,
ADD COLUMN "invoiceNotes" TEXT,
ADD COLUMN "bookingTerms" TEXT,
ADD COLUMN "privacyPolicyText" TEXT,
ADD COLUMN "demoModeEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "realPaymentsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "realAvailabilityEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "whatsappNotificationsEnabled" BOOLEAN NOT NULL DEFAULT false;
